server:
  port: 8888
  servlet:
    context-path: /boot

spring:
  datasource:
    druid:
      username: root
      password: 980518
      jdbc-url: jdbc:mysql://218.78.84.3:3306/boot?useUnicode=true&useCharacterEncoding=utf8&useSSL=false
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

--- #开发者
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 980518
    url: jdbc:mysql://218.78.84.3:3306/boot?useUnicode=true&useCharacterEncoding=utf8&useSSL=false

  # jpa
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


  #redis集群
  redis:
    password:
    host: localhost
    port: 6379
  #redis缓存数据ttl
  cache:
    redis:
      time-to-live: 60000
  #延时加载
#  main:
#    lazy-initialization: true

my:
  secret: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  map: {k1: 1,k2: 3}
  addr: ["baidu.com" , "jd.com"]
  password: 123456

top:
  takefly:
    open: ture

#mybatis
mybatis:
  type-aliases-package: top.takefly.boot.model
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
  mapper-locations: classpath:/mapper/*Mapper.xml

#redis

--- #测试环境
spring:
  profiles: test
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 980518
#    url: jdbc:mysql://218.78.84.3:3306/boot?useUnicode=true&useCharacterEncoding=utf8&useSSL=false

  # jpa
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  #延时加载
  main:
    lazy-initialization: true
my:
  secret: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  map: {k1: 1,k2: 3}
  addr: ["baidu.com" , "jd.com"]
  password: 123456

top:
  takefly:
    open: false


--- #生产环境
spring:
  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 980518
#    url: jdbc:mysql://218.78.84.3:3306/boot?useUnicode=true&useCharacterEncoding=utf8&useSSL=false

  # jpa
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  #延时加载
  main:
    lazy-initialization: true
my:
  secret: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  uuid: ${random.uuid}
  map: {k1: 1,k2: 3}
  addr: ["baidu.com" , "jd.com"]
  password: 123456

top:
  takefly:
    open: true